### ISSUE TITLE
Authentication returns Invalid credentials

### ISSUE THREAD

**Issue by Sun3** [Ovi/DummyJSON#11]
When you try to login via ```https://dummyjson.com/auth/login``` with username ```rshawe2``` and password ```OWsTbMUgFc``` it returns the message: ```{"message":"Invalid credentials"}```

I tried different username and passwords from ```https://dummyjson.com/users``` or from ```https://dummyjson.com/users?select=username,password``` with the same results.

Any ideas?
Thanks.

**Comment by Ovi** [comment]
Hey @Sun3,
I just tried with multiple credentials and they seem to be working fine.
![Screenshot from 2022-10-14 15-53-57](https://user-images.githubusercontent.com/23533420/195830697-49869afe-b859-4b89-8942-18287375490e.png)

However, if we remove the `headers: { 'Content-Type': 'application/json' },` from request, we get invalid credentials, because the body is not sent to the server as json.
![Screenshot from 2022-10-14 15-54-17](https://user-images.githubusercontent.com/23533420/195830946-2aa9930f-4114-4b48-96dc-68f3b3d98bd4.png)

**Comment by Sun3** [comment]
@Ovi Thank you, it's working.

**Comment by NjordJ** [comment]
Is it still working? Because when checking through postman and when developing an android application, I get a 400 error. I pass the 'Content-Type': 'application/json' to the header.

**Comment by Ovi** [comment]
Hey @NjordJ, I can confirm that it's working fine.
Maybe you can share postman request here so we can try.

**Comment by NjordJ** [comment]
@Ovi sharing postman collection with requests, checked another post request, it works fine, can't figure out what the problem is.

https://www.getpostman.com/collections/b55a025eb8e54300279c

**Comment by Ovi** [comment]
@NjordJ I see the issue.
![Screenshot from 2022-11-16 14-19-29](https://user-images.githubusercontent.com/23533420/202143424-5c830ec0-17d0-49b7-9cbd-252ea5f7adc5.png)

You have selected form data in data type, when we select form data, the content-type header is replaced by Postman.
Please select "raw" and "JSON" to send your data. (See the image attached for reference)

![Screenshot from 2022-11-16 14-21-04](https://user-images.githubusercontent.com/23533420/202143733-0007dc58-74cd-4157-91e5-7679d5cf6849.png)

**Comment by NjordJ** [comment]
@Ovi  Thanks for the help

**Comment by jerlam06** [comment]
I can confirm that there is an issue on postman, I am using RAW and JSON but still get Invalid Credentials.
